#!/usr/bin/env bash
# Installs nginx, configures index.html, 404 error and 301 redirect

# Prints message for updating and performing minor checks
echo -e "Updating and doing some minor checks...\n"

# Function to install packages if not already installed
function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "    Installing: $1$\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "    ${1} is already installed.\n"
    fi
}

# Install nginx
install nginx

echo -e "\nSetting up some minor stuff.\n"

# Allow Nginx HTTP traffic through firewall
sudo ufw allow 'Nginx HTTP'

# Set permissions and create necessary directories
if [ -d "/var/www" ]; then
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
else
    sudo mkdir -p /var/www
    sudo chown -R "$USER":"$USER" /var/www
    sudo chmod -R 755 /var/www
fi

# Create html and error directories
for dir in /var/www/{html,error}; do
    if ! [ -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

# Create index.html and error_404.html files
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# Backup the default nginx configuration
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

# Define the nginx server configuration
server_config="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
        rewrite ^ https://th3-gr00t.tk permanent;
    }
    error_page 404 /error_404.html;
    location = /error_404.html {
        internal;
    }
}"

# Apply the server configuration to the nginx default site
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

# Restart nginx service
if [ "$(pgrep -c nginx)" -le 0 ]; then
    sudo service nginx start
else
    sudo service nginx restart
fi
